version: '3.8'

services:
  app:
    build:
      # context: ./
      dockerfile: Dockerfile.multistage
    # working_dir: /app
    container_name: docker-go-do-it
    ports:
      - "8080:8080"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined